services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: rustcoon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rustcoon" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./migrations/postgres:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data:
